"""create-all

Revision ID: 96716b7c7fe2
Revises: 83debb2e61c4
Create Date: 2023-02-27 16:59:04.395629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96716b7c7fe2'
down_revision = '83debb2e61c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Username3', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'Username3')
    # ### end Alembic commands ###
