"""create-v4

Revision ID: e8c48c6803e2
Revises: 96716b7c7fe2
Create Date: 2023-02-27 17:01:07.839165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c48c6803e2'
down_revision = '96716b7c7fe2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Username4', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'Username4')
    # ### end Alembic commands ###
