"""create-v54

Revision ID: f5dadf9b4c78
Revises: f458182e028c
Create Date: 2023-02-27 17:03:40.896803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5dadf9b4c78'
down_revision = 'f458182e028c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
