"""create-finall

Revision ID: f6d91a33ca72
Revises: fb06205e3dae
Create Date: 2023-02-27 19:03:46.333803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d91a33ca72'
down_revision = 'fb06205e3dae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age213123213')
    op.drop_column('users', 'Username4')
    op.drop_column('users', 'age')
    op.drop_column('users', 'Username3')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Username3', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('age', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('Username4', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('age213123213', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
