"""create-546544

Revision ID: fb06205e3dae
Revises: f5dadf9b4c78
Create Date: 2023-02-27 17:04:28.496495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb06205e3dae'
down_revision = 'f5dadf9b4c78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age213123213', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age213123213')
    # ### end Alembic commands ###
